version: '3'

volumes:
  minio_data:
    driver: local
  flashcards_postgres_data:
    driver: local

services:
  postgres:
    image: postgres:15.6
    container_name: flashcards_postgres
    environment:
      - POSTGRES_USER=${FLASHCARDS_USERNAME}
      - POSTGRES_PASSWORD=${FLASHCARDS_PASSWORD}
      - POSTGRES_DB=${FLASHCARDS_DB}
    ports:
      - '5419:5432'
    volumes:
      - flashcards_postgres_data:/data/flashcards


  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z.fips
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/data


