server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5420/${FLASHCARDS_DB}
    username: ${FLASHCARDS_USERNAME}
    password: ${FLASHCARDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

minio:
  endpoint: ${MINIO_ENDPOINT}
  bucket-name: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}